//
//  MAPInteractor.swift
//  mickey
//
//  Created by Varun Iyer on 5/11/19.
//  Copyright (c) 2019 Michelle Friedman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

final class MAPInteractor {
    private func getMockMonumentData() -> [Monument] {
        
        
      
        
        return []
    }
  
}

// MARK: - Extensions -

extension MAPInteractor: MAPInteractorInterface {

    
    func getMonuments() -> [Monument] {
        return getMockMonumentData()
    }
    
}
