//
//  MAPInterfaces.swift
//  mickey
//
//  Created by Varun Iyer on 5/11/19.
//  Copyright (c) 2019 Michelle Friedman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MAPViewInterface: ViewInterface {
    func updateMonumentAnnotations(monuments: [Monument])
    func updateFriendAnnotations(friends: [User])
    func tapExpand()
    func tapCollapse()
    func setCamera(latitude: Double, longitude: Double)
}

protocol MAPPresenterInterface: PresenterInterface {
    func getMonuments() -> [Monument]
}

protocol MAPInteractorInterface: InteractorInterface {
    func getMonuments() -> [Monument]
}
