//
//  MAPPresenter.swift
//  mickey
//
//  Created by Varun Iyer on 5/11/19.
//  Copyright (c) 2019 Michelle Friedman. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MAPPresenter {

    // MARK: - Private properties -

    private let _view: MAPViewInterface
    private let _interactor: MAPInteractorInterface
    private var _monuments: [Monument]!
    private var _friends: [User]!

    // MARK: - Lifecycle -

    init(view: MAPViewInterface, interactor: MAPInteractorInterface) {
        _view = view
        _interactor = interactor
        
        _monuments = _interactor.getMonuments()
    }
}

// MARK: - Extensions -

extension MAPPresenter: MAPPresenterInterface {
    func getMonuments() -> [Monument] {
        return _monuments
    }
    
    func getFriends() -> [User] {
        return _friends
    }
}
